# Generated by Django 4.0.4 on 2022-04-25 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_event_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 25)),
        ),
        migrations.AlterField(
            model_name='story',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
