# Generated by Django 4.0.4 on 2022-04-25 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_event_date_alter_story_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='story',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
