# Generated by Django 4.0.4 on 2022-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_event_date_alter_story_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='ts',
            field=models.DateTimeField(default=None),
        ),
    ]
