# Generated by Django 4.0.4 on 2022-04-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_story_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
    ]
